import type { Config } from 'tailwindcss';

export const tailwindPreset = {
  theme: {
    colors: {
      primary: {
        50: 'rgb(var(--color-primary-50) / <alpha-value>)',
        100: 'rgb(var(--color-primary-100) / <alpha-value>)',
        200: 'rgb(var(--color-primary-200) / <alpha-value>)',
        300: 'rgb(var(--color-primary-300) / <alpha-value>)',
        400: 'rgb(var(--color-primary-400) / <alpha-value>)',
        500: 'rgb(var(--color-primary-500) / <alpha-value>)',
        600: 'rgb(var(--color-primary-600) / <alpha-value>)',
        700: 'rgb(var(--color-primary-700) / <alpha-value>)',
        800: 'rgb(var(--color-primary-800) / <alpha-value>)',
        900: 'rgb(var(--color-primary-900) / <alpha-value>)',
      },
      accent: {
        50: 'rgb(var(--color-accent-50) / <alpha-value>)',
        100: 'rgb(var(--color-accent-100) / <alpha-value>)',
        200: 'rgb(var(--color-accent-200) / <alpha-value>)',
        300: 'rgb(var(--color-accent-300) / <alpha-value>)',
        400: 'rgb(var(--color-accent-400) / <alpha-value>)',
        500: 'rgb(var(--color-accent-500) / <alpha-value>)',
        600: 'rgb(var(--color-accent-600) / <alpha-value>)',
        700: 'rgb(var(--color-accent-700) / <alpha-value>)',
      },
      success: {
        50: 'rgb(var(--color-success-50) / <alpha-value>)',
        100: 'rgb(var(--color-success-100) / <alpha-value>)',
        500: 'rgb(var(--color-success-500) / <alpha-value>)',
        600: 'rgb(var(--color-success-600) / <alpha-value>)',
        700: 'rgb(var(--color-success-700) / <alpha-value>)',
      },
      warning: {
        50: 'rgb(var(--color-warning-50) / <alpha-value>)',
        100: 'rgb(var(--color-warning-100) / <alpha-value>)',
        500: 'rgb(var(--color-warning-500) / <alpha-value>)',
        600: 'rgb(var(--color-warning-600) / <alpha-value>)',
        700: 'rgb(var(--color-warning-700) / <alpha-value>)',
      },
      danger: {
        50: 'rgb(var(--color-danger-50) / <alpha-value>)',
        100: 'rgb(var(--color-danger-100) / <alpha-value>)',
        500: 'rgb(var(--color-danger-500) / <alpha-value>)',
        600: 'rgb(var(--color-danger-600) / <alpha-value>)',
        700: 'rgb(var(--color-danger-700) / <alpha-value>)',
      },
      info: {
        50: 'rgb(var(--color-info-50) / <alpha-value>)',
        100: 'rgb(var(--color-info-100) / <alpha-value>)',
        500: 'rgb(var(--color-info-500) / <alpha-value>)',
        600: 'rgb(var(--color-info-600) / <alpha-value>)',
        700: 'rgb(var(--color-info-700) / <alpha-value>)',
      },
      surface: 'rgb(var(--surface-page) / <alpha-value>)',
      'surface-card': 'rgb(var(--surface-card) / <alpha-value>)',
      'surface-raised': 'rgb(var(--surface-raised) / <alpha-value>)',
      'surface-overlay': 'rgb(var(--surface-overlay) / <alpha-value>)',
      fg: 'rgb(var(--text-primary) / <alpha-value>)',
      'text-secondary': 'rgb(var(--text-secondary) / <alpha-value>)',
      'text-tertiary': 'rgb(var(--text-tertiary) / <alpha-value>)',
      border: 'rgb(var(--border-subtle) / <alpha-value>)',
      'border-default': 'rgb(var(--border-default) / <alpha-value>)',
      'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
    },
    borderRadius: {
      none: 'var(--radius-none)',
      xs: 'var(--radius-xs)',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
      '2xl': 'var(--radius-2xl)',
      '3xl': 'var(--radius-3xl)',
      full: 'var(--radius-full)',
    },
    boxShadow: {
      none: 'var(--elev-0)',
      'elev-1': 'var(--elev-1)',
      'elev-2': 'var(--elev-2)',
      'elev-3': 'var(--elev-3)',
      'elev-4': 'var(--elev-4)',
      'elev-5': 'var(--elev-5)',
      'elev-6': 'var(--elev-6)',
    },
    fontFamily: {
      sans: [
        'Inter',
        'system-ui',
        '-apple-system',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'sans-serif',
      ],
    },
    fontSize: {
      'display-xl': ['3rem', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
      'display-lg': ['2.25rem', { lineHeight: '1.15', fontWeight: '700', letterSpacing: '-0.01em' }],
      'display-md': ['1.875rem', { lineHeight: '1.2', fontWeight: '600' }],
      h1: ['1.5rem', { lineHeight: '1.25', fontWeight: '600' }],
      h2: ['1.25rem', { lineHeight: '1.3', fontWeight: '600' }],
      h3: ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
      'body-lg': ['1.125rem', { lineHeight: '1.5', fontWeight: '400' }],
      body: ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
      'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
      caption: ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
      'numeric-xl': ['2.5rem', { lineHeight: '1', fontWeight: '700' }],
      'numeric-lg': ['1.75rem', { lineHeight: '1.1', fontWeight: '600' }],
      numeric: ['1.125rem', { lineHeight: '1.2', fontWeight: '600' }],
      label: ['0.875rem', { lineHeight: '1.3', fontWeight: '500' }],
    },
    spacing: {
      0: '0',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      12: '48px',
      14: '56px',
      16: '64px',
      20: '80px',
      24: '96px',
    },
    transitionDuration: {
      fast: '100ms',
      normal: '200ms',
      slow: '300ms',
      page: '400ms',
    },
    transitionTimingFunction: {
      standard: 'var(--ease-standard)',
      emphasized: 'var(--ease-emphasized)',
      decel: 'var(--ease-decel)',
      accel: 'var(--ease-accel)',
    },
    extend: {},
  },
  plugins: [],
} satisfies Pick<Config, 'theme' | 'plugins'>;
